name: 정기 릴리즈 feat 커밋 추가

on:
  workflow_dispatch:
    inputs:
      sprint_number:
        type: number
        description: 스프린트 번호
        required: true

jobs:
  release-finish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: feature/${{ github.event.inputs.sprint_number }}sp

      # 브랜치 최신화
      - name: Update remote branches
        run: git remote update

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.20.0"

      - name: Add a feat Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git commit --allow-empty -m "feat: 정기 릴리즈를 위한 커밋"
          git push origin
