name: 릴리즈 브랜치 닫기

on:
  workflow_dispatch:
  repository_dispatch:
    types: [릴리즈 완료]
  # schedule:
  #   - cron: "0 9 * * 1"  # 예: 매주 월요일 오전 9시에 실행 (UTC 기준)

permissions:
  contents: write

jobs:
  release-finish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 브랜치 최신화
      - name: Update remote branches
        run: git remote update

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.20.0"

      - name: Install git flow
        run: |
          sudo apt-get update
          sudo apt-get install -y git-flow
          git flow init -d

      - name: Set Git user info
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update develop and master branch
        run: git checkout develop && git pull origin develop --allow-unrelated-histories && git checkout master && git pull origin master --allow-unrelated-histories

      - name: Get Release branch's name
        run: |
          TODAY_DATE=$(node -e 'const today = new Date(); console.log(`${today.getFullYear()}${String(today.getMonth() + 1).padStart(2, "0")}${String(today.getDate()).padStart(2, "0")}`)')
          echo "RELEASE_BRANCH_NAME=${TODAY_DATE}-0" >> $GITHUB_ENV

      # 릴리즈 브랜치 닫기 (TODO: wq 자동화)
      - name: Publish Release Branch
        run: |
          git flow release track ${{ env.RELEASE_BRANCH_NAME }}

          git flow release finish -Fpn ${{ env.RELEASE_BRANCH_NAME }}
