name: "[CD] Vapor Release Note Slack 알림"

on:
  workflow_dispatch:

jobs:
  on-success:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Get current package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.2.3
        with:
          path: packages/my-components/

      # 노션의 릴리즈 노트 링크 가져옴
      - name: Get Recent Release note
        env:
          NOTION_DATABASE_ID: ${{secrets.NOTION_DATABASE_ID}}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY}}
        run: |
          response=$(curl -X POST 'https://api.notion.com/v1/databases/${{env.NOTION_DATABASE_ID}}/query' \
            -H 'Authorization: Bearer ${{env.NOTION_API_KEY}}' \
            -H 'Content-Type: application/json' \
            -H 'Notion-Version: 2022-06-28' \
            -d '{
                    "sorts": [
                    {
                        "timestamp": "created_time",
                        "direction": "descending"
                    }
                    ],
                    "page_size": 1
                }')

          echo "RESPONSE=$response" >> $GITHUB_ENV

      - name: Get Release Note's url
        id: release-note-url
        uses: actions/github-script@v6
        with:
          script: |
            const { RESPONSE } = process.env;
            const data = JSON.parse(RESPONSE);
            const url = data.results.url;
            return url;

      - name: Send to Slack via Webhook
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          NOTION_LINK: ${{ steps.release-note-url.outputs.result }}
        run: |
          # 결합된 메시지를 Slack으로 전송
          curl -X POST --data-urlencode "payload={
            \"username\": \"GDS-bot\",
            \"attachments\": [
              {
                \"pretext\": \"*릴리즈노트* Vapor Packages ${{ steps.package-version.outputs.current-version }}(<"$NOTION_LINK" | 릴리즈 노트>)가 릴리즈 됐습니다 :tada:\",
                \"color\": \"#5094FA\",
              },
            ]
          }" "${{ secrets.SLACK_WEBHOOK_URL }}"

#   on-failure:
#     runs-on: ubuntu-latest
#     if: ${{ github.event.workflow_run.conclusion == 'failure' }}
#     steps:
#       - name: Get current package version
#         id: package-version
#         uses: martinbeentjes/npm-get-version-action@v1.2.3
#         with:
#           path: packages/vapor-components/
